### ISSUE TITLE
Add AAATA

### ISSUE THREAD

**Issue by vielmetti** [kona314/transit-fedilerts#1]
I realize that over time it might be hard to run this for every transit agency!

AAATA (aka "The Ride") serves the Ann Arbor area. Their data information is at

https://www.theride.org/business/software-developers

It looks like they have both a GTFS feed and an API. Is it possible to implement your alert system with this, or is more info or more data needed?

Eventually I'd hope for a bot to serve the `a2mi.social` Mastodon instance.

**Comment by kona314** [comment]
Thanks! I've contacted them for info. Currently, this is built for GTFS-realtime alert feeds only, and it's not clear to me if their API is custom/vendor-specific or meets the open standard. We'll see what they send me. I do intend to have a way to support other alert formats but it's not available just yet. 

Worth noting—Transit Fedilerts is a server in and of itself, it's not setup to power a bot within another instance. It's pretty lightweight by design though, I'm hoping to add a good number of agencies.

**Comment by kona314** [comment]
Available at @theride_aata@transit.alerts.social

**Comment by vielmetti** [comment]
@kona314 nice! I'll watch for traffic.

**Comment by vielmetti** [comment]
follow up at #10
